/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateUsersIndexRouteImport } from './routes/_private/users/index'
import { Route as PrivateTasksIndexRouteImport } from './routes/_private/tasks/index'
import { Route as PrivateProfileIndexRouteImport } from './routes/_private/profile/index'
import { Route as AuthVerifyIndexRouteImport } from './routes/_auth/verify/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PrivateUsersEmailIndexRouteImport } from './routes/_private/users/$email/index'
import { Route as AuthPasswordResetIndexRouteImport } from './routes/_auth/password/reset/index'
import { Route as AuthPasswordForgotIndexRouteImport } from './routes/_auth/password/forgot/index'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateUsersIndexRoute = PrivateUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTasksIndexRoute = PrivateTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileIndexRoute = PrivateProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthVerifyIndexRoute = AuthVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateUsersEmailIndexRoute = PrivateUsersEmailIndexRouteImport.update({
  id: '/users/$email/',
  path: '/users/$email/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthPasswordResetIndexRoute = AuthPasswordResetIndexRouteImport.update({
  id: '/password/reset/',
  path: '/password/reset/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPasswordForgotIndexRoute = AuthPasswordForgotIndexRouteImport.update({
  id: '/password/forgot/',
  path: '/password/forgot/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/verify/': typeof AuthVerifyIndexRoute
  '/profile/': typeof PrivateProfileIndexRoute
  '/tasks/': typeof PrivateTasksIndexRoute
  '/users/': typeof PrivateUsersIndexRoute
  '/password/forgot/': typeof AuthPasswordForgotIndexRoute
  '/password/reset/': typeof AuthPasswordResetIndexRoute
  '/users/$email/': typeof PrivateUsersEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/verify': typeof AuthVerifyIndexRoute
  '/profile': typeof PrivateProfileIndexRoute
  '/tasks': typeof PrivateTasksIndexRoute
  '/users': typeof PrivateUsersIndexRoute
  '/password/forgot': typeof AuthPasswordForgotIndexRoute
  '/password/reset': typeof AuthPasswordResetIndexRoute
  '/users/$email': typeof PrivateUsersEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_auth/verify/': typeof AuthVerifyIndexRoute
  '/_private/profile/': typeof PrivateProfileIndexRoute
  '/_private/tasks/': typeof PrivateTasksIndexRoute
  '/_private/users/': typeof PrivateUsersIndexRoute
  '/_auth/password/forgot/': typeof AuthPasswordForgotIndexRoute
  '/_auth/password/reset/': typeof AuthPasswordResetIndexRoute
  '/_private/users/$email/': typeof PrivateUsersEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/login/'
    | '/register/'
    | '/verify/'
    | '/profile/'
    | '/tasks/'
    | '/users/'
    | '/password/forgot/'
    | '/password/reset/'
    | '/users/$email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/verify'
    | '/profile'
    | '/tasks'
    | '/users'
    | '/password/forgot'
    | '/password/reset'
    | '/users/$email'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_private/'
    | '/api/auth/$'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_auth/verify/'
    | '/_private/profile/'
    | '/_private/tasks/'
    | '/_private/users/'
    | '/_auth/password/forgot/'
    | '/_auth/password/reset/'
    | '/_private/users/$email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof PrivateUsersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tasks/': {
      id: '/_private/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof PrivateTasksIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile/': {
      id: '/_private/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof PrivateProfileIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_auth/verify/': {
      id: '/_auth/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof AuthVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/users/$email/': {
      id: '/_private/users/$email/'
      path: '/users/$email'
      fullPath: '/users/$email/'
      preLoaderRoute: typeof PrivateUsersEmailIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_auth/password/reset/': {
      id: '/_auth/password/reset/'
      path: '/password/reset'
      fullPath: '/password/reset/'
      preLoaderRoute: typeof AuthPasswordResetIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/password/forgot/': {
      id: '/_auth/password/forgot/'
      path: '/password/forgot'
      fullPath: '/password/forgot/'
      preLoaderRoute: typeof AuthPasswordForgotIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
  AuthPasswordForgotIndexRoute: typeof AuthPasswordForgotIndexRoute
  AuthPasswordResetIndexRoute: typeof AuthPasswordResetIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
  AuthPasswordForgotIndexRoute: AuthPasswordForgotIndexRoute,
  AuthPasswordResetIndexRoute: AuthPasswordResetIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateRouteRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateProfileIndexRoute: typeof PrivateProfileIndexRoute
  PrivateTasksIndexRoute: typeof PrivateTasksIndexRoute
  PrivateUsersIndexRoute: typeof PrivateUsersIndexRoute
  PrivateUsersEmailIndexRoute: typeof PrivateUsersEmailIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateProfileIndexRoute: PrivateProfileIndexRoute,
  PrivateTasksIndexRoute: PrivateTasksIndexRoute,
  PrivateUsersIndexRoute: PrivateUsersIndexRoute,
  PrivateUsersEmailIndexRoute: PrivateUsersEmailIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
